# Generated by Django 5.2 on 2025-06-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
